version: '3.7'

services:
  longhorn-manager:
    image: rancher/longhorn-manager:v1.2.0
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    ports:
      - "9500:9500"
    volumes:
      - "longhorn:/var/lib/longhorn"
    networks:
      - longhorn-net

        #  longhorn-driver:
        #    image: rancher/longhorn-engine:v1.2.0
        #    deploy:
        #      mode: global
        #      placement:
        #        constraints:
        #          - node.role == worker
        #      resources:
        #        limits:
        #          memory: 512M
        #    volumes:
        #      - "longhorn:/var/lib/longhorn"
        #    networks:
        #      - longhorn-net
        #    sysctls:
        #      - net.core.somaxconn=65535

  longhorn-backend-1:
    image: rancher/longhorn-backend:v1.2.0
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == lnd
      resources:
        limits:
          memory: 512M
      restart_policy:
        condition: on-failure
    volumes:
      - "longhorn:/var/lib/longhorn"
      - "longhorn-backup:/backup"
    networks:
      - longhorn-net
    command: ["/usr/local/bin/longhorn-backend", "--listen", "0.0.0.0:9502", "--size", "0", "--backend", "tcp", "--tcp-address", "192.168.1.1:9502"]
    sysctls:
      - net.core.somaxconn=65535

  longhorn-backend-2:
    image: rancher/longhorn-backend:v1.2.0
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == nyc
      resources:
        limits:
          memory: 512M
      restart_policy:
        condition: on-failure
    volumes:
      - "longhorn:/var/lib/longhorn"
      - "longhorn-backup:/backup"
    networks:
      - longhorn-net
    command: ["/usr/local/bin/longhorn-backend", "--listen", "0.0.0.0:9502", "--size", "0", "--backend", "tcp", "--tcp-address", "192.168.1.2:9502"]
    sysctls:
      - net.core.somaxconn=65535

  longhorn-backend-3:
    image: rancher/longhorn-backend:v1.2.0
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == bng
      resources:
        limits:
          memory: 512M
      restart_policy:
        condition: on-failure
    volumes:
      - "longhorn:/var/lib/longhorn"
      - "longhorn-backup:/backup"
    networks:
      - longhorn-net
    command: ["/usr/local/bin/longhorn-backend", "--listen", "0.0.0.0:9502", "--size", "0", "--backend", "tcp", "--tcp-address", "192.168.1.3:9502"]
    sysctls:
      - net.core.somaxconn=65535

  longhorn-backend-4:
    image: rancher/longhorn-backend:v1.2.0
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == amd
      resources:
        limits:
          memory: 512M
      restart_policy:
        condition: on-failure
    volumes:
      - "longhorn:/var/lib/longhorn"
      - "longhorn-backup:/backup"
    networks:
      - longhorn-net
    command: ["/usr/local/bin/longhorn-backend", "--listen", "0.0.0.0:9502", "--size", "0", "--backend", "tcp", "--tcp-address", "192.168.1.4:9502"]
    sysctls:
      - net.core.somaxconn=65535

volumes:
  longhorn:
    driver: local
    driver_opts:
      type: none
      device: /store/longhorn
      o: bind
  longhorn-backup:
    driver: local
    driver_opts:
      type: none
      device: /store/longhorn/backup
      o: bind

networks:
  longhorn-net:
    driver: overlay

