FROM debian:bullseye

WORKDIR /data

EXPOSE 80 443

COPY ./acme-dns-auth.py /


RUN apt-get update \ 
&& apt-get install -y nginx certbot \
&& apt-get clean 

#CMD ["service","nginx","restart"]
CMD ["nginx","-g","daemon off;"]
#CMD ["tail","-f","/dev/null"]

