version: '3.7'

services:
  server-1:
    image: gluster/gluster-centos
    hostname: glusterfs-node-1
    environment:
      - GLUSTERFS_VOLUME_NAME=mail
      - GLUSTERFS_NODE_NAME=glusterfs-node-1
    volumes:
      - glusterd-lib:/var/lib/glusterd
      - glusterd-storage:/data
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == lnd
    networks:
      - glusterfs-net

  server-2:
    image: gluster/gluster-centos
    hostname: glusterfs-node-2
    environment:
      - GLUSTERFS_VOLUME_NAME=mail
      - GLUSTERFS_NODE_NAME=glusterfs-node-2
    volumes:
      - glusterd-lib:/var/lib/glusterd
      - glusterd-storage:/data
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == nyc
    networks:
      - glusterfs-net

  server-3:
    image: gluster/gluster-centos
    hostname: glusterfs-node-3
    environment:
      - GLUSTERFS_VOLUME_NAME=mail
      - GLUSTERFS_NODE_NAME=glusterfs-node-3
    volumes:
      - glusterd-lib:/var/lib/glusterd
      - glusterd-storage:/data
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == bng
    networks:
      - glusterfs-net

volumes:
  glusterd-lib:
    driver: local
    driver_opts:
      type: none
      device: /store/glusterfs/mail/lib
      o: bind
  glusterd-storage:
    driver: local
    driver_opts:
      type: none
      device: /store/glusterfs/mail/storage
      o: bind

networks:
  glusterfs-net:
    driver: overlay
    name: glusterfs-net

