version: '3.7'

services:
  glusterfs:
    image: gluster/gluster-centos
    command: "/bin/bash -c 'while :; do sleep 10; done'"
    volumes:
      - "gluster-lib:/var/lib/glusterd:Z"
      - "gluster-data:/data/gluster:Z"
    deploy:
      replicas: 3
      placement:
        constraints:
          - node.role == manager # run on manager nodes instead of worker nodes

  glusterfsd:
    image: gluster/gluster-centos
    command: "/bin/bash -c 'glusterd -N; while :; do sleep 10; done'"
    volumes:
      - "gluster-lib:/var/lib/glusterd:Z"
      - "gluster-data:/data/gluster:Z"
    deploy:
      replicas: 3
      placement:
        constraints:
          - node.role == manager # run on manager nodes instead of worker nodes

  glusterfsd2:
    image: gluster/gluster-centos
    command: "/bin/bash -c 'glusterd -N; while :; do sleep 10; done'"
    volumes:
      - "gluster-lib:/var/lib/glusterd:Z"
      - "gluster-data:/data/gluster:Z"
    deploy:
      replicas: 3
      placement:
        constraints:
          - node.role == manager # run on manager nodes instead of worker nodes

  glusterfs-client:
    image: gluster/gluster-centos
    volumes:
      - "gluster-lib:/var/lib/glusterd:Z"
      - "gluster-data:/data/gluster:Z"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    entrypoint: "/bin/bash"
    command:
      - "-c"
      - |
        gluster peer probe glusterfs.1.glusterfs.glusterfs_default &&
        gluster peer probe glusterfs.2.glusterfs.glusterfs_default &&
        gluster volume create gluster-volume replica 3 glusterfs.1.glusterfs.glusterfs_default:/data/gluster glusterfs.2.glusterfs.glusterfs_default:/data/gluster glusterfs.3.glusterfs.glusterfs_default:/data/gluster &&
        gluster volume start gluster-volume &&
        while :; do sleep 10; done

volumes:
  gluster-lib:
  gluster-data:

