version: "3.7"

services:
  mattermost:
    image: mattermost/mattermost-team-edition:latest
    depends_on:
      - mariadb
    environment:
      - MM_USERNAME=mmuser
      - MM_PASSWORD=mmpassword
      - MM_EMAIL=mmuser@example.com
      - MM_SITEURL=http://example.com
      - MM_CONFIG=mysql://mmuser:mmpassword@tcp(mariadb:3306)/mattermost?charset=utf8mb4,utf8&readTimeout=30s&writeTimeout=30s
      - MM_ENABLEBOTACCOUNTS=true
      - MM_BOTACCOUNTENABLED=true
      - MM_BOTACCOUNTUSERNAME=bot
      - MM_BOTACCOUNTPASSWORD=botpassword
      - MM_BOTACCOUNTDISPLAYNAME="Mattermost Bot"
        # ports:
        # - 8065:8065
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == bng
      restart_policy:
        condition: on-failure
    volumes:
      - /store/mattermost/mattermost-data:/mattermost/data
    networks:
      - mattermost-network
      - minio

  mariadb:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=mattermost
      - MYSQL_USER=mmuser
      - MYSQL_PASSWORD=mmpassword
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == bng
      restart_policy:
        condition: on-failure
    volumes:
      - /store/mattermost/mariadb-data:/var/lib/mysql
    networks:
      - mattermost-network

networks:
  mattermost-network:
    name: mattermost-net
  minio:
    external:
      name: minio_minio_distributed
